# Generated by Django 6.0.7 on 2026-07-23 17:06

import pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='data_nascimento',
            field=models.DateField(validators=[pacientes.validators.validate_data_nascimento], verbose_name='Data de Nascimento'),
        ),
    ]
