# Generated by Django 6.0.7 on 2026-07-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_pacientes_is_active_alter_pacientes_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('em_preparacao', 'Em Preparação'), ('em_procedimento', 'Em Procedimento'), ('recuperacao_pos_anestesica', 'Recuperação Pos-Anestésica'), ('no_quarto', 'No Quarto'), ('em_alta', 'Em Alta')], default='Aguardando', max_length=30),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
