# Generated by Django 6.0.7 on 2026-07-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_pacientes_status_pacientes_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do acompanhante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='pacientes.pacientes', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Inscrição de Notificação',
                'verbose_name_plural': 'Incrições de Notificações',
                'unique_together': {('Pacientes', 'email')},
            },
        ),
    ]
